# Generated by Django 4.2.11 on 2024-03-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(default='defaultmail@mymail.com', max_length=255, unique=True, verbose_name='email address')),
                ('phone', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bride_name', models.CharField(max_length=20)),
                ('bride_email', models.EmailField(max_length=254)),
                ('bride_phone', models.CharField(max_length=20)),
                ('groom_phone', models.CharField(max_length=20)),
                ('groom_email', models.EmailField(max_length=254)),
                ('groom_name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('registration_date', models.DateField()),
                ('wedding_date', models.DateField()),
                ('invitation_card', models.ImageField(upload_to='')),
            ],
        ),
    ]
