# Generated by Django 4.2.11 on 2024-03-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='wedding',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='invitation_card',
            field=models.ImageField(blank=True, upload_to='weddings/'),
        ),
    ]
