# Generated by Django 4.2.11 on 2024-04-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_user_managers_wedding_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wedding',
            name='events',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='registration_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
